#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# Save trace setting
_XTRACE_NEUTRON_SR=$(set +o | grep xtrace)
set +o xtrace

function neutron_plugin_create_nova_conf {
    :
}

function neutron_plugin_install_agent_packages {
    :
}

function is_neutron_ovs_base_plugin {
    return 1
}

function neutron_plugin_configure_debug_command {
    :
}

function neutron_plugin_configure_dhcp_agent {
    :
}

function neutron_plugin_configure_l3_agent {
    :
}

function neutron_plugin_configure_plugin_agent {

    AGENT_BINARY="$NEUTRON_BIN_DIR/neutron-sr-agent"
    iniset /$Q_PLUGIN_CONF_FILE securitygroup firewall_driver iptables_vrf

    # Install networking-sr
    dir=${GITDIR['networking-sr']}
    setup_package $dir

    # Install policy config
    mkdir -p $NEUTRON_CONF_DIR/policy.d
    cp $dir/etc/neutron/policy.d/srv6.conf $NEUTRON_CONF_DIR/policy.d

    iniset /$Q_PLUGIN_CONF_FILE sr segment_node_id $SEGMENT_NODE_ID
    iniset /$Q_PLUGIN_CONF_FILE sr segment_gw_id $SEGMENT_GW_ID
    iniset /$Q_PLUGIN_CONF_FILE sr srv6_interfaces $SRV6_INTERFACES

    neutron_service_plugin_class_add sr
}

function neutron_plugin_setup_interface_driver {
    local conf_file=$1
    # TODO: Adds sr interface_driver
    iniset $conf_file DEFAULT interface_driver sr
}


#function has_neutron_plugin_security_group {
#    # 1 means False here
#    return 0
#}

function neutron_plugin_check_adv_test_requirements {
    is_service_enabled q-agt && is_service_enabled q-dhcp && return 0
}


function has_neutron_plugin_security_group {
    return 1
}

# Restore xtrace
$_XTRACE_NEUTRON_SR
